version: "3.9"
services:

    nginx:
        container_name: hl-messenger-nginx
        build:
            context: docker
            dockerfile: development/nginx/Dockerfile
        ports:
            - "8001:80"
        volumes:
            - .:/app
        depends_on:
            - php-fpm
        networks:
            - hl-network-messenger

    php-fpm:
        container_name: hl-messenger-php-fpm
        build:
            context: docker
            dockerfile: development/php-fpm/Dockerfile
        environment:
            APP_ENV: ${APP_ENV}
            APP_DEBUG: ${APP_DEBUG}
            SENTRY_DSN: ${SENTRY_DSN}
            TARANTOOL_ENABLE: ${TARANTOOL_ENABLE}
            TARANTOOL_HOST: ${TARANTOOL_HOST}
            TARANTOOL_USER: ${TARANTOOL_USER}
            TARANTOOL_PASSWORD: ${TARANTOOL_PASSWORD}
            RABBITMQ_HOST: ${RABBITMQ_HOST}
            RABBITMQ_PORT: ${RABBITMQ_PORT}
            RABBITMQ_USER: ${RABBITMQ_USER}
            RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
            DB_DRIVER: ${DB_DRIVER}
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            DB_NAME: ${DB_NAME}
            DB_CHARSET: ${DB_CHARSET}
            JWT_ENCRYPTION_KEY: /run/secrets/jwt_encryption_key
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
        volumes:
            - .:/app
        secrets:
            - jwt_encryption_key
            - jwt_public_key
            - jwt_private_key
        networks:
            - hl-network-messenger

    php-cli:
        container_name: hl-messenger-php-cli
        build:
            context: docker
            dockerfile: development/php-cli/Dockerfile
        environment:
            APP_ENV: ${APP_ENV}
            APP_DEBUG: ${APP_DEBUG}
            SENTRY_DSN: ${SENTRY_DSN}
            TARANTOOL_ENABLE: ${TARANTOOL_ENABLE}
            TARANTOOL_HOST: ${TARANTOOL_HOST}
            TARANTOOL_USER: ${TARANTOOL_USER}
            TARANTOOL_PASSWORD: ${TARANTOOL_PASSWORD}
            RABBITMQ_HOST: ${RABBITMQ_HOST}
            RABBITMQ_PORT: ${RABBITMQ_PORT}
            RABBITMQ_USER: ${RABBITMQ_USER}
            RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
            DB_DRIVER: ${DB_DRIVER}
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            DB_NAME: ${DB_NAME}
            DB_CHARSET: ${DB_CHARSET}
        volumes:
            - .:/app
        networks:
            - hl-network-messenger

    proxysql:
        container_name: hl-proxysql
        build:
            context: docker
            dockerfile: development/sharding/proxysql/Dockerfile
        volumes:
            - proxysql:/var/lib/mysql
        networks:
            - hl-network-messenger
        ports:
            - "6033:6033"
            - "6032:6032"
        depends_on:
            - db-node-0
            - db-node-1
            - db-node-2

    db-node-0:
        platform: linux/x86_64
        container_name: hl-mysql-node-0
        restart: always
        build:
            context: docker
            dockerfile: development/sharding/mysql/Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - node-0:/var/lib/mysql
        networks:
            - hl-network-messenger

    db-node-1:
        platform: linux/x86_64
        container_name: hl-mysql-node-1
        restart: always
        build:
            context: docker
            dockerfile: development/sharding/mysql/Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - node-1:/var/lib/mysql
        networks:
            - hl-network-messenger

    db-node-2:
        platform: linux/x86_64
        container_name: hl-mysql-node-2
        restart: always
        build:
            context: docker
            dockerfile: development/sharding/mysql/Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - node-2:/var/lib/mysql
        networks:
            - hl-network-messenger

    phpmyadmin:
        container_name: hl-messenger-phpmyadmin
        image: phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            UPLOAD_LIMIT: 500M
        ports:
            - "7888:80"
        networks:
            - hl-network-messenger

    tarantool:
        container_name: hl-messenger-tarantool
        restart: always
        build:
            context: docker
            dockerfile: development/tarantool/Dockerfile
        ports:
            - "3301:3301"
        volumes:
            - ./var/tarantool:/var/lib/tarantool
        networks:
            - hl-network-messenger

    php-event-new-message:
        container_name: hl-messenger-event-new-message
        restart: always
        build:
            context: docker
            dockerfile: development/php-cli/Dockerfile
        environment:
            APP_ENV: ${APP_ENV}
            APP_DEBUG: ${APP_DEBUG}
            SENTRY_DSN: ${SENTRY_DSN}
            DB_DRIVER: ${DB_DRIVER}
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            DB_CHARSET: ${DB_CHARSET}
        volumes:
            - .:/app
        networks:
            - hl-network-messenger
        depends_on:
            - proxysql
        command: composer app messenger:consumer-new-message

volumes:
    node-0:
    node-1:
    node-2:
    proxysql:

networks:
    hl-network-messenger:
        driver: bridge

secrets:
    jwt_encryption_key:
        file: ./docker/development/secrets/jwt_encryption_key
    jwt_public_key:
        file: ./docker/development/secrets/jwt_public_key
    jwt_private_key:
        file: ./docker/development/secrets/jwt_private_key
